export const typography = {
  display: "var(--font-display)",
  body: "var(--font-body), var(--font-inter), system-ui, sans-serif",
  navFamily: "var(--font-poppins), var(--font-inter), system-ui, sans-serif",
  displayHero: {
    fontFamily: "var(--font-display)",
    fontSize: "clamp(3.7rem, 8vw, 6.5rem)",
    lineHeight: "0.9",
    letterSpacing: "-0.055em",
    fontWeight: 500,
  },
  displayStatement: {
    fontFamily: "var(--font-display)",
    fontSize: "clamp(2.9rem, 6vw, 4.7rem)",
    lineHeight: "0.92",
    letterSpacing: "-0.05em",
    fontWeight: 500,
  },
  displaySection: {
    fontFamily: "var(--font-display)",
    fontSize: "clamp(2.35rem, 4.6vw, 3.9rem)",
    lineHeight: "0.96",
    letterSpacing: "-0.045em",
    fontWeight: 500,
  },
  sectionEyebrow: {
    fontFamily: "var(--font-montserrat)",
    fontSize: "0.72rem",
    lineHeight: "1",
    letterSpacing: "0.34em",
    textTransform: "uppercase" as const,
    fontWeight: 600,
  },
  bodyLarge: {
    fontFamily: "var(--font-inter)",
    fontSize: "1.08rem",
    lineHeight: "1.85",
    letterSpacing: "-0.01em",
  },
  bodyStandard: {
    fontFamily: "var(--font-inter)",
    fontSize: "0.98rem",
    lineHeight: "1.8",
    letterSpacing: "-0.005em",
  },
  caption: {
    fontFamily: "var(--font-inter)",
    fontSize: "0.82rem",
    lineHeight: "1.6",
  },
  metadata: {
    fontFamily: "var(--font-montserrat)",
    fontSize: "0.7rem",
    lineHeight: "1.3",
    letterSpacing: "0.22em",
    textTransform: "uppercase" as const,
  },
  cta: {
    fontFamily: "var(--font-montserrat)",
    fontSize: "0.8rem",
    lineHeight: "1",
    letterSpacing: "0.22em",
    textTransform: "uppercase" as const,
    fontWeight: 700,
  },
  nav: {
    fontFamily: "var(--font-montserrat)",
    fontSize: "0.72rem",
    lineHeight: "1",
    letterSpacing: "0.24em",
    textTransform: "uppercase" as const,
    fontWeight: 600,
  },
  formLabel: {
    fontFamily: "var(--font-montserrat)",
    fontSize: "0.76rem",
    lineHeight: "1.2",
    letterSpacing: "0.18em",
    textTransform: "uppercase" as const,
    fontWeight: 600,
  },
} as const;
